# Generated by Django 4.1 on 2024-05-11 14:30

from django.db import migrations

import courses.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_subject_slug_alter_subject_title_video_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=courses.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
